apiVersion: v1
kind: ServiceAccount
metadata:
  name: crypto-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'crypto-app-role'
        vault.hashicorp.com/agent-inject-secret-database: 'secret/crypto-db'
        vault.hashicorp.com/agent-inject-template-database: |
          {{- with secret "secret/crypto-db" -}}
          export DB_USER="{{ .Data.data.username }}"
          export DB_PASSWORD="{{ .Data.data.password }}"
          {{- end -}}
    spec:
      serviceAccountName: crypto-sa
      containers:
      - name: node-app
        image: saharbe/portfolio-app-node:v3
        ports:
        - containerPort: 3000
        command: ["/bin/sh", "-c"]
        args:
          - |
            cd /usr/src/app || cd /app || echo "Using current dir"
            if [ -f /vault/secrets/database ]; then
              source /vault/secrets/database
            fi
            node index.js
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_NAME
          value: "mydb"
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort 
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080