apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-crypto-app
spec:
  provider:
    vault:
      server: 'http://vault.vault.svc.cluster.local:8200'
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: crypto-app-role
          serviceAccountRef:
            name: crypto-sa
            namespace: default
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crypto-db-external-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-crypto-app
    kind: ClusterSecretStore
  target:
    name: crypto-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: crypto-db
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: crypto-db
        property: password
