apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. The namespace where all these components will be deployed
namespace: crypto-wallet-app

# 2. List of all manifest files that ArgoCD should apply for this app
resources:
  - namespace.yaml
  - service-account.yaml
  - postgres.yaml
  - postgres-init-configmap.yaml
  - order-service.yaml
  - wallet-service.yaml
  - frontend.yaml
  - external-secret.yaml
  - hpa.yaml