apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: crypto-wallet-app
  labels:
    app: wallet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
        - name: wallet-service
          image: 079000477935.dkr.ecr.us-east-1.amazonaws.com/wallet-service:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKERS
              value: "kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092"
            - name: DB_HOST
              value: "postgres-db.rypto-wallet-app.svc.cluster.local"
            - name: DB_USER
              value: "myuser"
            - name: DB_PASSWORD
              value: "mypassword"
            - name: DB_NAME
              value: "mydb"
            - name: DB_PORT
              value: "5432"
