apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-custom
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/SaharBe/crypto-wallet-service.git'
    targetRevision: HEAD
    path: k8s/apps/monitoring
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true